/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package teistris.view;

/**
 * Este dialogo permite selecionar modo de xogo (clasico ou extendido)
 *
 * @author Xocas
 */
public class JDialogGamemode extends javax.swing.JDialog {

    //Flag que indica se o modo de xogo é extendido ou clasico
    private boolean extendedGamemode;

    /**
     * @return se esta no modo de xogo extendido
     */
    public boolean isExtendedGamemode() {
        return extendedGamemode;
    }

    /**
     * Establece o modo de xogo
     *
     * @param extendedGamemode false = clasico, true = extendido
     */
    public void setExtendedGamemode(boolean extendedGamemode) {
        this.extendedGamemode = extendedGamemode;
    }

    /**
     * Creates new form JDialogGamemode
     */
    public JDialogGamemode(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessage = new javax.swing.JLabel();
        jButtonClasico = new javax.swing.JButton();
        jButtonExtendido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modo de Xogo");
        setModal(true);

        jLabelMessage.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelMessage.setText("Escolla un modo de xogo");

        jButtonClasico.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonClasico.setText("Clasico");
        jButtonClasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClasicoActionPerformed(evt);
            }
        });

        jButtonExtendido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonExtendido.setText("Extendido");
        jButtonExtendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtendidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButtonClasico)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonExtendido)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelMessage)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClasico)
                    .addComponent(jButtonExtendido))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Empeza a partida en modo clasico
     *
     * @param evt
     */
    private void jButtonClasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClasicoActionPerformed
        extendedGamemode = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonClasicoActionPerformed
    /**
     * Empeza a partida en modo extendido
     *
     * @param evt
     */
    private void jButtonExtendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtendidoActionPerformed
        extendedGamemode = true;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExtendidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGamemode dialog = new JDialogGamemode(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClasico;
    private javax.swing.JButton jButtonExtendido;
    private javax.swing.JLabel jLabelMessage;
    // End of variables declaration//GEN-END:variables
}
