package teistris.view;

/**
 * Este dialogo permite selecionar modo de xogo (clasico ou extendido)
 *
 * @author Xocas
 */
public class JDialogGamemode extends javax.swing.JDialog {

    //Flag que indica se o set de pezas é extendido ou clasico
    private boolean extendedPieces;
    //Indica modo de xogo
    private int gamemode;

    /**
     * @return se esta no modo de xogo extendido
     */
    public boolean isExtendedPieces() {
        return extendedPieces;
    }

    /**
     * Establece o modo de xogo
     *
     * @param extendedGamemode false = clasico, true = extendido
     */
    public void setExtendedPieces(boolean extendedGamemode) {
        this.extendedPieces = extendedGamemode;
    }

    /**
     *
     * @return id do modo de xogo
     */
    public int getGamemode() {
        return gamemode;
    }

    /**
     * Establece modo de xogo
     *
     * @param gamemode
     */
    public void setGamemode(int gamemode) {
        this.gamemode = gamemode;
    }

    /**
     * Creates new form JDialogGamemode
     */
    public JDialogGamemode(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessage = new javax.swing.JLabel();
        jComboPiecesSet = new javax.swing.JComboBox<>();
        jLabelPiecesSet = new javax.swing.JLabel();
        jLabelGamemode = new javax.swing.JLabel();
        jComboGamemode = new javax.swing.JComboBox<>();
        jButtonAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modo de Xogo");
        setModal(true);

        jLabelMessage.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelMessage.setText("Configure a sua partida:");

        jComboPiecesSet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboPiecesSet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clásico", "Extendido" }));

        jLabelPiecesSet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPiecesSet.setText("Escolla un set de pezas:");

        jLabelGamemode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelGamemode.setText("Escolla un modo de xogo:");

        jComboGamemode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboGamemode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Caos", "CaosExtremo" }));

        jButtonAccept.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAccept.setText("Comezar Partida");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPiecesSet)
                            .addComponent(jLabelGamemode))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboGamemode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboPiecesSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonAccept)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPiecesSet)
                    .addComponent(jComboPiecesSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGamemode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGamemode))
                .addGap(18, 18, 18)
                .addComponent(jButtonAccept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        // TODO add your handling code here:
        extendedPieces = jComboPiecesSet.getSelectedIndex() != 0;
        gamemode = jComboGamemode.getSelectedIndex();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGamemode.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGamemode dialog = new JDialogGamemode(new javax.swing.JFrame(),
                                                             true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JComboBox<String> jComboGamemode;
    private javax.swing.JComboBox<String> jComboPiecesSet;
    private javax.swing.JLabel jLabelGamemode;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPiecesSet;
    // End of variables declaration//GEN-END:variables
}
